<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5735ad80c99d014c580a7cefad532f38
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Puleeno\\React\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Puleeno\\React\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5735ad80c99d014c580a7cefad532f38::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5735ad80c99d014c580a7cefad532f38::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5735ad80c99d014c580a7cefad532f38::$classMap;

        }, null, ClassLoader::class);
    }
}
