<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit69e1b554b9eff9714e980c494eeb8f74
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Platovies\\TheMovieDb\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Platovies\\TheMovieDb\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit69e1b554b9eff9714e980c494eeb8f74::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit69e1b554b9eff9714e980c494eeb8f74::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit69e1b554b9eff9714e980c494eeb8f74::$classMap;
        }, null, ClassLoader::class);
    }
}
