<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit848131f43a8494557fba9e6b380d35c6
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Platovies\\Admin\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Platovies\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit848131f43a8494557fba9e6b380d35c6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit848131f43a8494557fba9e6b380d35c6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit848131f43a8494557fba9e6b380d35c6::$classMap;

        }, null, ClassLoader::class);
    }
}
