<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5c4a6a0c05396dae53042b82404bb561
{
    public static $files = array (
        '9c429d4cf6e538d01218b18b7bf42c5e' => __DIR__ . '/../..' . '/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Puleeno\\Layout\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Puleeno\\Layout\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5c4a6a0c05396dae53042b82404bb561::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5c4a6a0c05396dae53042b82404bb561::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5c4a6a0c05396dae53042b82404bb561::$classMap;
        }, null, ClassLoader::class);
    }
}
